apiVersion: apps/v1                                    
kind: Deployment         
metadata:            
  name: meta-service-deployment
  labels:                                                                                                      
    app: meta-service   
                           
spec:                     
  replicas: 2                                          
  selector:       
    matchLabels:        
      app: meta-service                                
                                                       
  template:                                            
    metadata:       
      labels:                                          
        app: meta-service                              
    spec:                  
      containers: 
      - name: meta-service                             
        image: selectdb-ms:latest                                                                              
        imagePullPolicy: IfNotPresent                                                                          
        ports:                                                                                                 
        - containerPort: 5000                          
          name: brpc-port
        volumeMounts:
        - name: config
          mountPath: /opt/selectdb/meta-service/conf
          readOnly: true
      volumes:             
      - name: config
        projected:                                     
          sources:
          - configMap:  
              name: ms-configmap                       
          - configMap:                                 
              name: test-cluster-config                
              items:
              - key: "cluster-file"                    
                path: "fdb.cluster"    

---                                                                                                            
apiVersion: v1                                         
kind: Service                                                                                                  
metadata:                                                                                                      
  name: ms-service                                                                                             
spec:                                                  
  selector:              
    app: meta-service
  ports:                                               
  - name: meta-service-port                                                                                    
    port: 5000          
    protocol: TCP          
    targetPort: brpc-port 
                                                       
---               
apiVersion: v1          
kind: ConfigMap                                        
metadata:                                              
  name: ms-configmap                                   
data:               
  selectdb_cloud.conf: |                               
    brpc_listen_port = 5000                            
    brpc_num_threads = -1  
    fdb_cluster_file_path = ./conf/fdb.cluster 
    http_token = greedisgood9999

    # // doris txn config
    label_keep_max_second = 259200
    expired_txn_scan_key_nums = 1000

    # // logging
    log_dir = ./log/
    # info warn error
    log_level = info
    log_size_mb = 1024
    log_filenum_quota = 10
    log_immediate_flush = false

    # // recycler config
    recycle_interval_seconds = 3600
    retention_seconds = 259200
    recycle_concurrency = 16

    # //max stage num
    max_num_stages = 40


